import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-mosaic-component/react-mosaic-component.css";
import { MosaicProvider } from "@/components/layout/MosaicProvider";
import { CopilotKit } from "@copilotkit/react-core";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CopilotKit
          // Using the self-hosted runtime URL from environment variables
          runtimeUrl={process.env.NEXT_PUBLIC_COPILOTKIT_RUNTIME_URL}
          agent={process.env.NEXT_PUBLIC_COPILOTKIT_AGENT_NAME}
        >
          <MosaicProvider>
            {children}
          </MosaicProvider>
        </CopilotKit>
      </body>
    </html>
  );
}
